serviceAccount:
  create: true
  name: external-dns

publicConfig:
  image:
    controller:
      repository: registry.k8s.io/external-dns/external-dns
      tag: v0.18.0
      pullPolicy: IfNotPresent
    provider:
      repository: volcengine/external-dns-provider
      tag: v0.2.0
      pullPolicy: IfNotPresent

userConfig:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  nodeSelector:
    kubernetes.io/os: linux
  Resources:
    controller:
      Requests:
        Cpu: "250m"
        Memory: "128Mi"
      Limits:
        Cpu: "500m" 
        Memory: "256Mi"
    provider:
      Requests:
        Cpu: "250m"
        Memory: "128Mi"
      Limits:
        Cpu: "500m" 
        Memory: "256Mi"
  args:
    controller:
      sources:
        - service
        - ingress
      interval: 30s
      logLevel: info
      domainFilters: []       # @schema type: []string; domain filter, if empty, will filter all domain; default: null
      labelFilter:            # @schema type: [string,null]; default: null
      policy: upsert-only     # @schema enum:[create-only, sync, upsert-only]; type:string; default: "upsert-only"
      registry: txt           # @schema enum:[txt, noop]; default: "txt"
      txtOwnerId:             # @schema type:[string, null]; default: null
      txtPrefix: externaldns-%{record_type}. # @schema type:[string, null]; default: externaldns-%{record_type}.
      txtWildcardReplacement: wildcard # @schema type:[string, null]; default: wildcard
    provider:
      logLevel: false
  env:
    provider:
      vpc:
      region: cn-beijing
      privatezoneEndpoint: open.volcengineapi.com
      stsEndpoint: sts.volcengineapi.com
      credentialsProvider: aksk     # @schema enum:[aksk, irsa]; default: "aksk"
      secretName:
      oidcRoleTrn: